version: "3"
services:
  golang:
    container_name: "golang"
    build: ./docker/go
    volumes:
      - ./app:/usr/local/project:delegated
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    container_name: "mysql"
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=go_api_boilerplate
      - MYSQL_ROOT_PASSWORD=password
volumes:
  mysql_db:
    driver: local