CREATE TABLE
IF NOT EXISTS `users`
(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR
(255)
) ENGINE = InnoDB DEFAULT CHARSET = utf8
;
CREATE TABLE
IF NOT EXISTS `posts`
(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT UNSIGNED NOT NULL,
    `body` TEXT
) ENGINE = InnoDB DEFAULT CHARSET = utf8
;